apiVersion: apps/v1
kind: Deployment
metadata:
  name: login-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: login-ui
  template:
    metadata:
      labels:
        app: login-ui
    spec:
      containers:
        - name: login-ui
          image: krishnna/jenkins_repo:${BUILD_NUMBER}
          ports:
            - containerPort: 80
