FROM jenkins/jenkins:lts

USER root

RUN apt-get update && apt-get install -y \
    curl ca-certificates gnupg lsb-release \
 && curl -fsSL https://get.docker.com | sh \
 && usermod -aG docker jenkins

USER jenkins
